version: '3.8'

services:

  mongodb:
    image: mongo:5.0.3
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017/productdb --quiet"

  postgres:
    image: postgres:14.1
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=customerdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"

  cassandra:
    image: cassandra:4.0.1
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
      - "7199:7199"
      - "9160:9160"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
