spring:
  application:
    name: customer-api
  data:
    couchbase:
      auto-index: true
      bucket-name: customers
  couchbase:
    connection-string: couchbase://127.0.0.1
    username: Administrator
    password: password

runner:
  num-customers: 10

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
