spring:
  application:
    name: product-api
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/productdb

runner:
  num-products: 100

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
